### ISSUE TITLE
unrecognized arguments: -p

### ISSUE THREAD

**Issue by Roise-yue** [renatahodovan/grammarinator#129]
When I use the latest version of grammarinator, there is no parameter - p for grammarinator-generate

**Comment by renatahodovan** [comment]
@Roise-yue Yes, the generated Unlexers and Unparsers got merged into a single Generator class in the new version. As a consequence, the CLI of `gramarinator-generate` has also changed: it expects to receive a reference to the generator class in `package.module.class` format (instead of `-l` and `-p`). See an example [here](https://github.com/renatahodovan/grammarinator#working-example) and the detailed documentation [here](https://grammarinator.readthedocs.io/en/latest/guide/test_generation.html).
