### ISSUE TITLE
Latest release is out of date

### ISSUE THREAD

**Issue by NickGeek** [renatahodovan/grammarinator#22]
Hi,
The latest release on `pip` (19.3) is currently out of date with `master` and is missing a few features.

Also, this project looks really cool!

**Comment by renatahodovan** [comment]
@NickGeek Hi Nick! I'm glad to hear that you like grammarinator! You are right, the latest features are not released yet, since there are a few further things that I'd like to put into the next one. However, I hope that we are close now. Until then you can install the latest version from git (if that works for you(?)).

**Comment by NickGeek** [comment]
Installing from git worked for me. Just tried out integrating the tool with JUnit and it's already found some issues with my parser, so thanks for saving me loads of time 😄

**Comment by renatahodovan** [comment]
You're very welcome! :D May I ask which project was it used for (if it's public)?

**Comment by NickGeek** [comment]
I'm using it for my research project at university. My supervisor and I made a formal object calculus for a language that allows you to use Functional Reactive Programming to declaratively define actor systems. I'm writing a proof of concept compiler to go alongside all of the formal logic.

It's not done yet but I'll be sure to post all the code and everything publically when I submit in a couple months.
