### ISSUE TITLE
No generator, no whitespace? Please help

### ISSUE THREAD

**Issue by docfate111** [renatahodovan/grammarinator#33]
How do I generate a <generator>? None of the tests have whitespace and the input often gives invalid characters.
I got the g4 for https://github.com/antlr/grammars-v4/blob/master/javascript/javascript/
```
grammarinator-process JavaScriptParser.g4 JavaScriptLexer.g4 -o out --no-actions

grammarinator-generate -p out/JavaScriptUnparser.py -l out/JavaScriptUnlexer.py -r program -d 30 -n 3000

```
MacOS Python3.9
What is a generator do I need to write a generator program?
How do I write a transformer or change the grammar to add spaces? (Looking at the closed issue this is the solution but I have no idea what a transformer is).

**Comment by docfate111** [comment]
Now I am getting
```
Traceback (most recent call last):
  File "/usr/local/bin/grammarinator-generate", line 8, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python3.8/dist-packages/grammarinator/generate.py", line 281, in execute
    with Generator(unlexer_path=args.unlexer, unparser_path=args.unparser, rule=args.rule, out_format=args.out,
  File "/usr/local/lib/python3.8/dist-packages/grammarinator/generate.py", line 71, in __init__
    self.unlexer_cls = import_entity('.'.join([unlexer, unlexer]))
  File "/usr/local/lib/python3.8/dist-packages/grammarinator/generate.py", line 59, in import_entity
    return getattr(importlib.import_module('.'.join(steps[0:-1])), steps[-1])
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "output/JavaScriptUnlexer.py", line 9, in <module>
    from JavaScriptLexerBase import JavaScriptLexerBase
ModuleNotFoundError: No module named 'JavaScriptLexerBase'
 ```
 from the second command.

**Comment by renatahodovan** [comment]
Hey @docfate111 !

The way you generate the generator is correct. With the command above the generated fuzzer, aka. generator will be placed in the out folder of your current working directory.

The way you use the grammarinator-generate utility is outdated: instead of referencing the generator file, you must use fully qualified names. In this case the command should look like:

```
grammarinator-generate JavaScriptGenerator.JavaScriptGenerator -r program -o tests/%d.js \
    -d 30 -n 3000 \
    --sys-path out/
```

The `--sys-path` argument ensures that the out directory is placed on the sys-path, hence referencing the generator with fully qualified name will work. Another example of the usage is available from the [readme](https://github.com/renatahodovan/grammarinator#working-example).

Your next problem will be that the original grammar specifies a superclass for both the [lexer](https://github.com/antlr/grammars-v4/blob/master/javascript/javascript/JavaScriptLexer.g4#L35) and the [parser](https://github.com/antlr/grammars-v4/blob/master/javascript/javascript/JavaScriptParser.g4#L35). These superclasses give additional information to the parser, which are useless for the fuzzer, ofc. Hence, I suggest to comment out these lines for now. If you still need some superclasses for your generated fuzzer, then you should write them for yourself.

To add spaces to your output you need to write a serializer. Serializers and transformers are similar things, they both work on grammar trees, but while serializers produce string outputs, transformers produce tree outputs. So, to add spaces to your output you need a serializer. A basic serializer, that inserts spaces after every UnparserRule (i.e., inner node of the grammar tree) is implemented [here](https://github.com/renatahodovan/grammarinator/blob/master/grammarinator/runtime/serializer.py). To use it you should extend the previous generator command as shown below (serializers are also referred with fully qualified names just like the generator):

```
grammarinator-generate JavaScriptGenerator.JavaScriptGenerator -r program -o tests/%d.js \
    --serializer=grammarinator.runtime.serializer.simple_space_serializer \
    -d 30 -n 3000 \
    --sys-path out/
```

**Comment by akosthekiss** [comment]
@docfate111 I hope serializers (plus the additional details in @renatahodovan 's reply) did solve your problem. Closing this issue now as 5 months have passed since the Q and the A. However, if the problem still stands, feel free to re-open this issue (or open a new one).
