### ISSUE TITLE
Can't set alt weights

### ISSUE THREAD

**Issue by bendrissou** [renatahodovan/grammarinator#67]
Is there a way to assign weights/probabilities to grammar alternatives?

**Comment by renatahodovan** [comment]
Hi @bendrissou !

Sure, you can assign weights to alternatives and there are multiple way of doing it:

1) Inline the weights right into the grammar file (they can be any number, don't need to be normalised, but the sum of the weights must be greater than 0. The weigths of the unchanged alternatives (i.e., the default value) are 1.), e.g.,:

```antlr
start:
    rule1
  | {100}? rule2
  | {0.01}? rule3
  ;
```

2) Or instead of assigning constant values, Python expressions can also be used that return a numerical value:

```antlr
start:
    { condition1() }? rule1
  | { condition2() + 3 }? rule2
  | rule3
  ;
```

3) If you don't prefer editing the grammar itself then you can define custom model classes that override the default choice and quantification implementation. The best way of doing it is to inherit from [DispatchingModel](https://github.com/renatahodovan/grammarinator/blob/master/grammarinator/runtime/dispatching_model.py) and override the decision making alternation:

```py
import random

from grammarinator.runtime import DispatchingModel

class CustomModel(DispatchingModel):

    def choice_start(self, node, idx, weights):
        # Override the decision of the first alternation (indexed from 0) in rule `start`.
        if idx == 0:
            weights[0] = 0  # Disable alternative 0.
            weights[2] *= 10  # Increase the weight of alternative 3.
            return random.choices(range(len(weights)), weights=weights)[0]
```

I hope it helps!

**Comment by bendrissou** [comment]
Thank you for the detailed answer. I didn't know we can specify weights. It was not mentioned in the paper. Only Actions were elaborated. Specifying weights is very useful when stress-testing targets. I wonder if there are other features I am missing.

**Comment by renatahodovan** [comment]
I think we can close this now.
