### ISSUE TITLE
Add support for generating case insensitive tests

### ISSUE THREAD

**Issue by marcospassos** [renatahodovan/grammarinator#8]
Our grammar is case insensitive, hence most tests look like the following:

```
aBc mAtcHes CdA
AbC mAtcHes cDa
```

However, it isn't relevant for us, so we've created a transformer that converts all `UnlexerRule`'s to lowercase. The problem is that now more than 50% of the tests are duplicated.

Do you have any idea of how to handle this?

**Comment by renatahodovan** [comment]
It's not an easy question since you expect from the generator to be prepared for a post-process step, which is independent from its logic. However, if you approach it from the generator side then perhaps you can solve the issue.

Some options in the grammar (thinking aloud):
- This is what we have now: `A: [Aa];`
- This rule is equivalent to the above: `A: 'A' | 'a';`
- With semantic predicates, we can 'disable' the capital letter: `A: {0}? 'A' | 'a';`
- But then we could also omit that alternative completely: `A: 'a';`

However, all the above means changing the grammar.


The other option is to inherit a custom unlexer that you can use to override the appropriate token definitions. E.g.:

```py
class CustomTestUnlexer(TestUnlexer):

    def A(self):
        return 'a'

    def B(self):
        return 'b'

etc...
```

After this you can refer this unlexer while generating:

```
grammarinator-generate -l CustomTestUnlexer -p TestUnparser -r domain
```

**Comment by renatahodovan** [comment]
@marcospassos Did any of the above help?

**Comment by marcospassos** [comment]
@renatahodovan, sorry for the late reply. The later option is pretty clean and worked very well. Thank you!
